# Generated by Django 4.2.4 on 2023-10-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.TextField(blank=True),
        ),
    ]
