# Generated by Django 4.2.4 on 2023-10-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_search_history_profile_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='search_history',
            field=models.TextField(),
        ),
    ]
